// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5LezNGLC988OYqq-HS09_rypJePOl0GQ',
    appId: '1:824368866611:web:9fe40173cc83b6197f0a46',
    messagingSenderId: '824368866611',
    projectId: 'ya-tasks-c9f06',
    authDomain: 'ya-tasks-c9f06.firebaseapp.com',
    storageBucket: 'ya-tasks-c9f06.appspot.com',
    measurementId: 'G-YLCX0MCEYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZ-fetca_G2y0JiltUXMhXVdSZ2KlA4k',
    appId: '1:824368866611:android:4915de5d211566bd7f0a46',
    messagingSenderId: '824368866611',
    projectId: 'ya-tasks-c9f06',
    storageBucket: 'ya-tasks-c9f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ts23tJVDTjn5mw6C6iCV01ZQzmPUEUs',
    appId: '1:824368866611:ios:6ff38d90b4e7fe737f0a46',
    messagingSenderId: '824368866611',
    projectId: 'ya-tasks-c9f06',
    storageBucket: 'ya-tasks-c9f06.appspot.com',
    iosClientId:
        '824368866611-dv2aqf29623bi8pq3er7l77alomueq8k.apps.googleusercontent.com',
    iosBundleId: 'com.goliksim.yatodo.yaTodolist',
  );
}
