include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
  

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude: [lib/**.freezed.dart, lib/**.g.dart]