name: ya_todolist
description: Homework application for Yandex MDS (ШМР).
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  #hw1
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.2
  #hw2
  flutter_bloc: ^8.1.3
  uuid: ^3.0.7
  equatable: ^2.0.5
  dio: ^5.2.1+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  #hw3
  device_info_plus: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  integration_test:
    sdk: flutter
  #hw4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_flavor: ^3.1.1
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_analytics: ^10.4.4
  firebase_remote_config: ^4.2.4
  path_provider: ^2.0.15



dev_dependencies:
  #hw2
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  #hw3
  hive_generator: ^2.0.0
  flutter_test: 
    sdk: flutter
  mocktail: ^0.3.0
  #hw4
  freezed: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf        
        - asset: assets/fonts/Roboto-Medium.ttf
  