name: Flutter CI

on: push
  #pull_request:
  #    branches:
  #      - master
  #      - main
  #  push:
  #    branches:
  #      - master
  #      - main
  #    paths-ignore:
  #      - "docs/**"
  #      - ".vscode/**"

jobs:
  analyze:
    name: Run analyzer and formatter
    runs-on: ubuntu-latest
    #timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Setup flutter actions
        uses: subosito/flutter-action@v2
        with:
          #channel: 'stable'
          flutter-version: '3.0.5'
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
  test:
    name: Run tests
    runs-on: ubuntu-latest
    #timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup flutter actions
        uses: subosito/flutter-action@v2
        with:
          #channel: 'stable'
          flutter-version: '3.0.5'
          cache: true
      - run: flutter pub get
      - run: flutter test
        id: test
      - if: ${{ failure() && steps.test.conclusion == 'failure' }}
        name: 'Upload test failures'
        uses: actions/upload-artifact@v3
        with:
          name: test-failures
          path: test/failures
          retention-days: 5
  build:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
      - name: "Build the apk"
        run:  flutter pub get && flutter build apk -t lib/main.dart  --flavor=prod  --release
      #- name: Push to Releases
      #  uses: ncipollo/release-action@v1
      #  with:
      #    artifacts: 'build\app\outputs\flutter-apk\app-prod-release.apk'
      #    tag: v1.0.${{ github.run_number }}
      #    token: ${{ secrets.TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-prod-release.apk
      - name: "Deploy artifact to Firebase App Distribution"
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: CI_Group
          file: build/app/outputs/flutter-apk/app-prod-release.apk

